### ISSUE TITLE
netbank AG not working - Uncaught Fhp\Dialog\Exception\FailedRequestException: Request Failed: Unknown error

### ISSUE THREAD

**Issue by danielsippel** [mschindler83/fints-hbci-php#44]
`PHP Fatal error:  Uncaught Fhp\Dialog\Exception\FailedRequestException: Request Failed: Unknown error in /Users/dsippel/code/fints-hbci-php/lib/Fhp/Dialog/Dialog.php:129
Stack trace:
#0 /Users/dsippel/code/fints-hbci-php/lib/Fhp/FinTs.php(135): Fhp\Dialog\Dialog->sendMessage(Object(Fhp\Message\Message))
#1 /Users/dsippel/code/fints-hbci-php/Samples/statement_of_account.php(28): Fhp\FinTs->getSEPAAccounts()
#2 {main}
  thrown in /Users/dsippel/code/fints-hbci-php/lib/Fhp/Dialog/Dialog.php on line 129`

Error response contains:
"HIRMG:3:2+9050::Die Nachricht enthält Fehler.+9800::Dialog abgebrochen+9110::Ungültige Auftragsnachricht?: Unbekannter Aufbau."

It is the 4th response coming from FinTS server in this statement_of_account.php run.

Best,
Daniel

**Comment by danielpieper** [comment]
I had the same problem and solved it by passing the bank routing code as string.

**Comment by framelabs** [comment]
Same Error here with Sparda Bank Munic

Fatal error: Uncaught Fhp\Dialog\Exception\FailedRequestException: Request Failed: Unknown error in C:\xampp\htdocs\banking\vendor\mschindler83\fints-hbci-php\lib\Fhp\Dialog\Dialog.php:129 Stack trace: #0 C:\xampp\htdocs\banking\vendor\mschindler83\fints-hbci-php\lib\Fhp\FinTs.php(135): Fhp\Dialog\Dialog->sendMessage(Object(Fhp\Message\Message)) #1 C:\xampp\htdocs\banking\saldo.php(27): Fhp\FinTs->getSEPAAccounts() #2 {main} thrown in C:\xampp\htdocs\banking\vendor\mschindler83\fints-hbci-php\lib\Fhp\Dialog\Dialog.php on line 129
