### ISSUE TITLE
GLS getStatement -> Request Failed: Die Nachricht enthält Fehler

### ISSUE THREAD

**Issue by CodingTanna** [mschindler83/fints-hbci-php#85]
Hi,
I tried to get the statement from a GLS Account, but it throws an exception(ING-Diba works fine). I like to fix it, but I have no idea, wheres the specification for the messages.

> PHP 7.0.22-0ubuntu0.16.04.1 Development Server started at Mon Nov 27 10:17:21 2017
Listening on http://localhost:8082
Document root is /home/user/NetBeansProjects/bankcheck
Press Ctrl-C to quit.
[Mon Nov 27 10:17:31 2017] PHP Fatal error:  Uncaught Fhp\Dialog\Exception\FailedRequestException: **Request Failed:  Die Nachricht enthält Fehler. (TRE) in /home/user/NetBeansProjects/bankcheck/vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php:129**
Stack trace:
#0 /home/user/NetBeansProjects/bankcheck/vendor/mschindler83/fints-hbci-php/lib/Fhp/FinTs.php(194): Fhp\Dialog\Dialog->sendMessage(Object(Fhp\Message\Message))
#1 /home/user/NetBeansProjects/bankcheck/index.php(45): Fhp\FinTs->getStatementOfAccount(Object(Fhp\Model\SEPAAccount), Object(DateTime), Object(DateTime))
#2 {main}
  thrown in /home/user/NetBeansProjects/bankcheck/vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php on line 129
[Mon Nov 27 10:17:31 2017] 127.0.0.1:53440 [200]: / - Uncaught Fhp\Dialog\Exception\FailedRequestException: Request Failed: Die Nachricht enthält Fehler. (TRE) in /home/user/NetBeansProjects/bankcheck/vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php:129
Stack trace:
#0 /home/user/NetBeansProjects/bankcheck/vendor/mschindler83/fints-hbci-php/lib/Fhp/FinTs.php(194): Fhp\Dialog\Dialog->sendMessage(Object(Fhp\Message\Message))
#1 /home/user/NetBeansProjects/bankcheck/index.php(45): Fhp\FinTs->getStatementOfAccount(Object(Fhp\Model\SEPAAccount), Object(DateTime), Object(DateTime))
#2 {main}
  thrown in /home/user/NetBeansProjects/bankcheck/vendor/mschindler83/fints-hbci-php/lib/Fhp/Dialog/Dialog.php on line 129

Thank you for this library, kind regards Tanna

**Comment by CodingTanna** [comment]
Duplicate of #93
